// Database
export const DATA_SOURCE = 'DATA_SOURCE';

// Repositories
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const WALLET_REPOSITORY = 'WALLET_REPOSITORY';
export const BALANCE_REPOSITORY = 'BALANCE_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const CURRENCY_REPOSITORY = 'CURRENCY_REPOSITORY';
